Added recursive option
ajryan/RptToXml pull request #53
Opened 2022-11-02 16:29 UTC by Icare67

I needed to recursively convert a complete hierarchy of directories. I added the recursive option for my needs. Take it if you are interested.

2022-11-02 21:57 UTC, ajryan commented
Thanks for this! Just a few comments.

2022-11-02 21:57 UTC, ajryan requested changes

2022-11-02 21:57 UTC, ajryan commented on RptToXml/Program.cs
> +				Console.WriteLine("Usage: RptToXml.exe < -r | RPT filename | wildcard> [outputfilename]");
Can we add a line to the usage output that describes how `-r` works?

2022-11-02 21:57 UTC, ajryan commented on RptToXml/Program.cs
> +					Trace.WriteLine("No reports matched the wildcard.");
This should be console.writeline, not trace - we ahven't hooked up the trace listener yet.

2022-11-02 21:57 UTC, ajryan commented on RptToXml/Program.cs
> +					Trace.WriteLine("No reports matched the wildcard.");
Or move the tracelistener init aabove rptPAths init as it was before

2022-11-03 16:51 UTC, Icare67 commented
Here are the requested changes

2022-11-03 17:12 UTC, ajryan approved these changes
Thanks for this!

2022-11-03 17:12 UTC, merged